micronaut:
  application:
    name: productMs
  server:
    port: 8080
datasource:
  driver-class-name: org.postgresql.Driver
  db-type: postgres
  dialect: POSTGRES
  username: postgres
  password: root123
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
eureka:
  client:
    registration:
      enabled: true
    defaultZone: ${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}
